//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAgent.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderMessage
    {
        public int pk_id { get; set; }
        public string user_name { get; set; }
        public string message { get; set; }
        public System.DateTime send_date { get; set; }
        public int fk_order { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
